const products = [
    {id: '1', name: 'Scott Spark RC 900 WC 900', category: 'BicicletasMTB', price: 'U$S 8900', stock: 100, description: 'La bicicleta Scott Spark RC 900 World Cup 2021 es la creación de suspensión integral para XCO que ha sido fabricada con un solo objetivo: ¡subir a lo más alto del podio! Con ella, subirás los montes más duros como un avión y descenderás con total seguridad para garantizarte la victoria del día. Presenta la horquilla RockShox SID Ultimate RD3 con 110 mm de recorrido y barras más anchas. ', imageUrl: 'https://f.fcdn.app/imgs/1ab3ab/albanes.com.uy/albauy/280c/webp/catalogo/98674_98674_1/800x800/bicicleta-scott-mtb-doble-suspencion-spark-900-rc-world-cup-axs-unica.jpg'},
    {id: '2', name: 'Trek Madone SL 6 Disc', category: 'BicicletasRuta', price: 'U$S 5250', stock: 80, description: 'La TREK Madone SL 6 Disc te ofrece el rendimiento aerodinámico avanzado y la calidad de manejo versátil de nuestra bici de carrera definitiva a un gran precio. Tiene ruedas aerodinámicas, un desacoplador IsoSpeed que suaviza el camino, poderosos frenos de disco hidráulicos y una elegante apariencia que inspira velocidad.', imageUrl: 'https://sparta.cl/media/catalog/product/m/a/madonesl6_22_35177_a_primary.jpg?quality=80&bg-color=255,255,255&fit=bounds&height=550&width=600&canvas=600:550'},
    {id: '3', name: 'Multi Herramienta Serfas ', category: 'Herramientas', price: 'U$S 23', stock: 50, description: 'Herramientas incluidas: 6, 5, 4, 3, llaves Allen de 2 mm, herramienta de cadena, destornilladores Phillips y de cabeza plana, T25 Torx, llave de radios Súper compacto Especificaciones: Número de herramientas: 11 Peso: 146 gramos ', imageUrl: 'https://f.fcdn.app/imgs/246184/albanes.com.uy/albauy/4e30/webp/catalogo/923658_923658_1/800x800/kit-de-herramientas-serfas-unica.jpg'},
    {id: '4', name: 'Scott Rc Team 20', category: 'Equipos', price: 'U$S 90', stock: 30, description: 'Luce como un profesional, rueda como un profesional. Muestrate con gran estilo mientras disfrutas de un rendimiento de pelotón profesional con un corte ajustado. Hecho de tela de poliéster de microfibra, este jersey extratranspirable es ideal para tus rodadas más difíciles en los días más cálidos.', imageUrl: 'https://f.fcdn.app/imgs/351614/scott-montevideo.com.uy/bscouy/a8bd/webp/catalogo/264832_72_1/2000-2000/camiseta-scott-rc-team-20-manga-corta-negro-gris.jpg'}
]

export const mFetch = (id) => new Promise ((res, rej)=>{
    setTimeout (()=> {
        res(id? products.find(product => product.id === id) : products)
    }, 2000)
})
